export const ALL_ROOMS_SUCCESS = 'ALL_ROOMS_SUCCESS';
export const ALL_ROOMS_FAILED = 'ALL_ROOMS_FAILED';

export const ROOM_DETAILS_SUCCESS = 'ROOM_DETAILS_SUCCESS';
export const ROOM_DETAILS_FAILED = 'ROOM_DETAILS_FAILED';

export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS';
export const NEW_REVIEW_FAILED = 'NEW_REVIEW_FAILED';
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET';
export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SSR_DATA = 'SSR_DATA';
